name: Build App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8 for ${{ matrix.arch }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Build executable with PyInstaller for ${{ matrix.arch }}
      run: |
        pyinstaller --onefile --noconsole --icon=favicon.ico --name "PPSUC-OneClickLogin-${{ matrix.arch }}" PPSUC-OneClickLogin.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.arch }}
        path: dist/*
